---

- hosts: telegraf
  tasks:
    - name: "Installing packages on CentOS"
      yum:
        name: which
        state: present
      when:
        - ansible_pkg_mgr == 'yum' or ansible_pkg_mgr == 'dnf'

    - name: "Installing packages on Debian"
      apt:
        name:
          - wget
          # - gpg
        state: present
      when:
        - ansible_pkg_mgr == 'apt'

    - name: "Installing packages on Suse"
      zypper:
        name:
          - sysvinit-tools
          - insserv-compat
          - aaa_base
        state: present
      when:
        - ansible_os_family == 'Suse'
